name: Generate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Generate
      run: |
        python3 generate.py "https://zzzzzzyt.github.io"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generate blog"
        git push
